# Generated by Django 2.2.6 on 2019-11-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='1255 E University Dr', max_length=500),
        ),
    ]
